[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geo_evalute"
version = "0.2"
description = "geo_evalute"
dependencies = [
    "sympy",
    "scipy",
    "math-verify",
    "pylatexenc"
]

[tool.setuptools]
packages = ["geo_evalute"]